#!/usr/bin/env python3
import sys
from os.path import dirname, realpath

sys.path.insert(0, dirname(realpath(__file__)))

from computorv1.cli import main  # noqa: E402

try:
    sys.exit(main(sys.argv[1:]))
except MemoryError:
    print("computor: internal error: MemoryError", file=sys.stderr)
    sys.exit(70)
except Exception as error:
    print(f"computor: internal error: {type(error).__name__}: {error}", file=sys.stderr)
    sys.exit(70)
